version: '3'
services:
  appcontainer:
    build:
      context: .
#      dockerfile: Dockerfile
      args:
#        This works but the hard coded name sucks a bit (why does the maven plugin not work here?)
        JAR_FILE: /spring-boot-jms-tutorial-1.0.0.jar
    ports:
    - "4000:8080"
  activemqcontainer:
    image: "rmohr/activemq"
    ports:
    - "8161:8161"
  mongocontainer:
    image: "mongo"
    # Add the lines below allows mongo's data survive the container being deleted since the data is saved locally on my machine
    # Taking it out saves all data only within the container and therefore is removed when the container is deleted
#    volumes:
#    - "~/mongo-data:/data/db"